# ---Environment Configs---
env_name: brax

scenario:
  name: barkour
  task_name: barkour

kwargs: {
  backend: mjx
}

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return
